# Generated by Django 4.2.1 on 2023-05-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_likedata_user_id_alter_posts_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
